# Generated by Django 5.2.1 on 2025-05-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='exercise_media/'),
        ),
    ]
